
# Feature Heatmap

```{r echo = FALSE, warning=FALSE, message = FALSE, fig.width = 10, fig.height = 10}
# Here's some info about the heatmap
tags$li(paste("The values shown in this heatmap are expression levels of", input$hm_scale, "scale."))
tags$li(paste0("The features shown in this heatmap have ranks range from ", input$feature_range[1], " to ", input$feature_range[2], " based on ranking by ", input$hm_rank_method, "."))
```

```{r echo = FALSE, warning=FALSE, message = FALSE, fig.width = 10, fig.height = 10}

if(input$hm_feature_tool == 1){ # heatmap.2
    if(is.null(hm_data()) || is.null(hm_sp_dend()) || is.null(hm_ft_dend())) return ()
    if(input$hm_sp_order_type == 'hc' && input$hm_ft_order_type == 'hc') {
        dend1 <- 'both'
    } else if(input$hm_sp_order_type == 'hc' && input$hm_ft_order_type != 'hc') {
        dend1 <- 'column'
    } else if(input$hm_sp_order_type != 'hc' && input$hm_ft_order_type == 'hc') {
        dend1 <- 'row'
    } else {
        dend1 <- 'none'
    }
    if(!is.null(plot_specs$info)) {
            gplots::heatmap.2(as.matrix(hm_data()), scale="none", Rowv = hm_ft_dend(), Colv = hm_sp_dend(), dendrogram=dend1, trace="none", col=hmcol$val, key.par=list(cex.axis=0.7), key.title=NA, key.xlab="  ", key.ylab=NA, keysize=.7, density.info="density", revC=T, cexCol = 1.2, margins=c(10,15),
                      ColSideColors = plot_specs$color)
            legend("topright", legend = unique(plot_specs$info), bty="n", fill = plot_specs$legend_color, text.col = plot_specs$legend_color, border=FALSE, y.intersp = 1.2, cex = 0.9)
    }
    else
        gplots::heatmap.2(as.matrix(hm_data()), scale="none", Rowv = hm_ft_dend(), Colv = hm_sp_dend(), dendrogram=dend1, trace="none", col=hmcol$val, key.par=list(cex.axis=0.7), key.title=NA, key.xlab="  ", key.ylab=NA, keysize=.7, density.info="density", revC=T, cexCol = 1.2, margins=c(8,6))

    } else {
    if(is.null(hm_data()) || is.null(hm_sp_dend()) || is.null(hm_ft_dend())) return ()
    d3heatmap::d3heatmap(as.matrix(hm_data()), scale="none", Rowv = hm_ft_dend(), Colv = hm_sp_dend(), dendrogram="both", colors=hmcol$val, revC=F, margins=c(8,6))
}


```

