
# SCDE Error Modeling

## Model Fit

```{r echo = FALSE, warning=FALSE, message = FALSE, fig.width = 8, fig.height = 6}
    if(is.null(r_data$scde_ifm)) return()
    DT::datatable(r_data$scde_ifm,options = list(scrollX = TRUE, scrollY = "250px", searching=F, order = list(list(5, 'asc')) , orderClasses = T))
```

```{r echo = FALSE, warning=FALSE, message = FALSE}
   if(nrow(r_data$scde_invalid) == 0){
               valid_msg1 <- "Fits for all your cells are valid."
   } else {
        valid_msg1 <- paste("Fits for", paste(rownames(r_data$scde_invalid), collapse = ', '), "are abnormal, and these samples will be removed from SCDE analysis. (Please note that these samples are also removed from the above table)")
    }
        
    print(valid_msg1)
```

## Probability of Transcript-detection Failures

```{r echo = FALSE, warning=FALSE, message = FALSE, fig.width = 8, fig.height = 6}
if(is.null(r_data$scde_ifm)) return()
    # get failure probabilities on the expresison range
    o.fail.curves <- scde::scde.failure.probability(r_data$scde_ifm,magnitudes=log((10^r_data$scde_prior$x)-1))
    par(mfrow=c(1,1),mar = c(3.5,3.5,0.5,0.5), mgp = c(2.0,0.65,0), cex = 1);
    
    plot(c(),c(),xlim=range(r_data$scde_prior$x),ylim=c(0,1),xlab="expression magnitude (log10)",ylab="drop-out probability")
    
    sp <- colnames(o.fail.curves)
    nSamples <- length(sp)
    colorMin = 1
    colorMax = nSamples
    # colorRamp produces custom palettes, using values between 0-1
    colorFunction = colorRamp(c("black", "blue", "red"))
    zMin = colorMin
    zMax = colorMax
    zDiff = zMax - zMin
    z = zMin:zMax
    zScaled = (z - zMin) / zDiff
    # Apply colorRamp
    zMatrix = colorFunction(zScaled)
    # switch to hexadecimal representation and sort to be consistent with colorFactor.
    zColors = sort(rgb(zMatrix[,1], zMatrix[,2], zMatrix[,3], maxColorValue=255))
    
    # create an empty character vector that will be used to store the line colors. This is necessary to color the legend.
    colorsUsed = character(nSamples)

    for(i in 1:nSamples) {
        # using the sample name means the column order in colorFactorSorted file doesn't have to match the order in the counts file
        sample = sp[i]
        color = zColors[i]
        colorsUsed[i] = color
        lines(x=r_data$scde_prior$x,y=o.fail.curves[,sample], type="l", lty=i, lwd=1.5, cex=1, col=color)
    }
    legend("topright", legend=sp, col=colorsUsed, lty=1:nSamples, lwd=1.8, cex=0.8)
```


