
# Feature Correlation Heatmap

## Heatmap.2

**Correlation method:** `r input$cor_ft_method`

```{r echo = FALSE, warning=FALSE, message = FALSE, fig.width = 10, fig.height = 10}
if(is.null(data0()) || nrow(r_data$df) > 500) return ()
    feature_cor <- cor(t(data0()), method = input$cor_ft_method)

    hclustfun1 = function(x, method=input$cor_ft_agglo_method, ...) hclust(x, method=method, ...)
    
    if(input$cor_ft_dist == "corr1") {
        distfun1 = function(c) as.dist(1 - c)
    } else if(input$cor_ft_dist == "corr2") {
        distfun1 = function(c) as.dist(1 - abs(c))
    }

    gplots::heatmap.2(feature_cor, scale="none", Rowv = T, symm=TRUE, dendrogram="both", 
              distfun=distfun1, 
              hclustfun = hclustfun1, 
              trace="none", col=hmcol$val, key.par=list(cex.axis=1), key.title=NA, key.xlab="  ", key.ylab=NA, keysize=1, density.info="density", revC=T, margins=c(8,6))
```


## D3heatmap

```{r echo = FALSE, warning=FALSE, message = FALSE,fig.width = 8, fig.height = 6}
    # You can remove this code chunk if you only need the heatmap.2 version
    if(is.null(data0()) || nrow(r_data$df) > 500) return ()
    feature_cor <- cor(t(data0()), method = input$cor_ft_method)
    
    hclustfun1 = function(x, method=input$cor_ft_agglo_method, ...) hclust(x, method=method, ...)
    
    if(input$cor_ft_dist == "corr1") {
        distfun1 = function(c) as.dist(1 - c)
    } else if(input$cor_ft_dist == "corr2") {
        distfun1 = function(c) as.dist(1 - abs(c))
    }
    
    d3heatmap::d3heatmap(feature_cor, scale="none", Rowv = T,
              distfun=distfun1, 
              hclustfun = hclustfun1, 
              dendrogram="both", colors=hmcol$val, revC=T)
```
