
# K-means Clustering

## Clustering results (Table)

```{r echo = FALSE, warning=FALSE, message = FALSE}
    if(is.null(km1())) return()
    if(is.null(r_data$group) || length(unique(r_data$group)) < 2)
    {
        tbl <- as.data.frame(table(km1()$cluster))
        colnames(tbl) <- c("Group", "Number of samples assigned")
        DT::datatable(tbl, options = list(searching = FALSE))
    } else {
        sample_gp <- r_data$group
        names(sample_gp) <- r_data$sample_name
        tbl <- as.data.frame.matrix(table(km1()$cluster, sample_gp))
        colnam <- names(tbl)
        names(tbl) <- sapply(colnam, function(x) paste("Is", x))
        rownam <- rownames(tbl)
        rownames(tbl) <- sapply(rownam, function(x) paste("Allocated to cluster", x))
        DT::datatable(tbl, options = list(searching = FALSE))
    }

```

## Clustering results (Assignment)

```{r echo = FALSE, warning=FALSE, message = FALSE}
    DT::datatable(km_assign_tbl(), options = list(scrollX = TRUE, scrollY = "400px", lengthMenu = c(20, 50, 100)))
```
